### ISSUE TITLE
Arch Linux?

### ISSUE THREAD

**Issue by xcellardoor** [hurricanehrndz/docker-browser-box#1]
Hi,

Tried running it and am getting this, please ask any and all questions, I'm keen to get this working :)

```╭─cellardoor@glow  ~  
╰─$ browser-box firefox samcater.com                                                                                                                                                                                          1 ↵
which: no browser-box in (/usr/sbin:/usr/bin:/sbin:/bin)
Cleaning up stopped browser-box instances...
cat: /etc/timezone: No such file or directory
Starting firefox...
invalid value ":/home/browser/.config/google-chrome" for flag --volume: bad format for volumes: :/home/browser/.config/google-chrome
See 'docker run --help'.
╭─cellardoor@glow  ~  
╰─$```

**Comment by hurricanehrndz** [comment]
Did you run the install command? There should be info on how to install in the READ.me.

If you clone the git repo into your home directory. Change directories to it. And then execute the following command:

make install

**Comment by hurricanehrndz** [comment]
Okay. I think i see some issues. I will test under a different user

**Comment by hurricanehrndz** [comment]
Should be fixed, I updated the readme so that you can install and run directly from my docker hub repo. If you wish to pass the timezone to the container since the file /etc/timezone doesn't exist, please use the timezone variable. 

i.e --env TIMEZONE=US/Mountain

**Comment by xcellardoor** [comment]
You may want to take another look at how this box tries to launch itself. For example I installed your copy from the docker hub (will try a manual build from GIT later). For now it says:

````
cellardoor at glow in [~]   
12:20:51 › browser-box firefox google.com
which: no browser-box in (/usr/sbin:/usr/bin:/sbin:/bin)
Cleaning up stopped browser-box instances...
Starting firefox...
Unable to find image 'cellardoor/browser-box:latest' locally
````

Which means it is trying to launch the browser-box but from my user. But my user didn't install the box, your user hurricane did, as it was built on your machine.

Sorry to keep finding problems! Will try building from Git instead now.

**Comment by xcellardoor** [comment]
Okay so I quickly built your image with the tag 'cellardoor/browser-box', which seems to have worked better for it. But nothing shows up on my screen, all I get is:

````
cellardoor at glow in [~/github/docker/docker-browser-box]  on git:master ✔︎  2c1f308 "Fixing issue 1."
12:26:03 › browser-box firefox google.com     
which: no browser-box in (/usr/sbin:/usr/bin:/sbin:/bin)
Cleaning up stopped browser-box instances...
Starting firefox...

cellardoor at glow in [~/github/docker/docker-browser-box]  on git:master ✔︎  2c1f308 "Fixing issue 1."
12:26:12 › 
````

**Comment by hurricanehrndz** [comment]
That is interesting. You should have gotten the firefox setup. Instead of using browser-box, use the firefox binary in /usr/local/bin or the chrome or chromium one of them should work. In the mean I will gix the issue with the repository name.

**Comment by hurricanehrndz** [comment]
Just updated the image on dockerhub. This should fix what repo the wrapper script should be pointing to. If you build from git, it will be pointing to your local image and if you install from the hub it should point to my repo on the docker hub. 

PS Thank you for finding all these issues.

**Comment by xcellardoor** [comment]
You're welcome, I enjoy helping to iron out the bugs. 

Getting better...!

````
cellardoor at glow in [~]   
22:13:37 › docker run -it hurricane/browser-box:latest firefox               
Adding user `browser' ...
Adding new user `browser' (1000) with group `browser' ...
Creating home directory `/home/browser' ...
Copying files from `/etc/skel' ...

(process:25): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Error: no display specified

cellardoor at glow in [~]   
22:13:43 › 
````

I tried passing /usr/local/bin/firefox but it said there was no such executable.

**Comment by xcellardoor** [comment]
Also running it this way doesn't actually make a window pop-up, and docker ps says nothing is running:

````
cellardoor at glow in [~]   
22:16:30 › browser-box firefox google.com
which: no browser-box in (/usr/sbin:/usr/bin:/sbin:/bin)
Cleaning up stopped browser-box instances...
Starting firefox...

cellardoor at glow in [~]   
22:16:34 › 
````

**Comment by hurricanehrndz** [comment]
Ops I guess I should have been more descriptive, if you ran the install command properly like in the README you should have several files in /usr/local/bin, one of them been firefox. Just try and run that file and see what happens.

**Comment by hurricanehrndz** [comment]
Okay, would you be open to remote support of some kind so I can get a better idea of what is going on.

**Comment by xcellardoor** [comment]
I re-ran this installation script as instructed by the README - 
````
docker run -it --rm \
  --volume /usr/local/bin:/target \
  --env BROWSER_BOX_REPO=hurricane \
  hurricane/browser-box:latest install
````

I've also just done the /usr/local/bin/firefox and also chromium-browser. All that is doing is launching my regular firefox session. 

Sorry but no remote support will be allowed to this machine.

**Comment by hurricanehrndz** [comment]
Ok, no worries about the remote support. Can you launch one of the browsers that is not installed on your os.  Perhaps the tor?

**Comment by xcellardoor** [comment]
Here you go:

````cellardoor at glow in [~]   
22:35:08 › /usr/local/bin/tor-browser 
which: no tor-browser in (/usr/sbin:/usr/bin:/sbin:/bin)
Cleaning up stopped browser-box instances...
Starting tor-browser...

cellardoor at glow in [~]   
22:36:59 › 
````

But again, nothing appears.

**Comment by hurricanehrndz** [comment]
I would check your X11 server and settings. It should work, try running xhost +local:root

**Comment by hurricanehrndz** [comment]
You are using x11 and not Wayland right?

**Comment by xcellardoor** [comment]
Just did that command as you suggested to open up my X11 but nothing happened. Yes I'm on X11 not Wayland. 

I'm not convinced that, despite running the install, the commands are being mapped properly. If I were to run firefox from 'directly inside' the container I get a whole different response:

````
cellardoor at glow in [~]   
22:44:30 › docker run -t hurricane/browser-box:latest firefox  
Adding user `browser' ...
Adding new user `browser' (1000) with group `browser' ...
Creating home directory `/home/browser' ...
Copying files from `/etc/skel' ...

(process:26): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Error: no display specified

cellardoor at glow in [~]   
22:44:43 › 
````

AHA! Nevermind as I was writing this I thought about borrowing some of Jess Frazelle's code, when run like this I get a clean and brand-new Firefox window pop up:

````cellardoor at glow in [~]   
22:45:31 › docker run -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY hurricane/browser-box:latest firefox
Adding user `browser' ...
Adding new user `browser' (1000) with group `browser' ...
Creating home directory `/home/browser' ...
Copying files from `/etc/skel' ...

(process:26): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

cellardoor at glow in [~]   
22:46:11 › 
````

**Comment by hurricanehrndz** [comment]
Glad to hear, the wrapper should take care of that though. If you re-run with the wrapper you should see and then run docker inspect on the resulting container you should see the X11 sockert and the display passed on.

**Comment by hurricanehrndz** [comment]
The only thing I can think that could be exhibiting the issue you describe is if ARCH for some reason does not create the DISPLAY environment variable.

**Comment by xcellardoor** [comment]
When I run just the wrapper, it doesn't do anything at all as described earlier. Just opens another window of my main Arch Linux copy of Firefox. I'm not entirely sure what to do, but for now at least I seem to have found a way to workaround it.

**Comment by hurricanehrndz** [comment]
Delete line 133, 134, 135 in the wrapper script browser box, that will stop it from launching your copy of firefox. Then run docker inspect firefox, you should be able to see the volumes and environment variable which were used to create the container.

**Comment by xcellardoor** [comment]
Did that, now it has gone back to not launching anything at all, but you're right the mount is there:
````
cellardoor at glow in [~]   
23:00:25 › /usr/local/bin/firefox
Cleaning up stopped browser-box instances...
Starting firefox...

cellardoor at glow in [~]   
23:00:40 › 


-------------


    "Mounts": [
        {
            "Source": "/tmp/.X11-unix",
            "Destination": "/tmp/.X11-unix",
            "Mode": "",
            "RW": true
        },
````

**Comment by hurricanehrndz** [comment]
What about the environment variable for display.

**Comment by xcellardoor** [comment]
````
cellardoor at glow in [~]   
23:05:31 › docker inspect firefox | grep DISPLAY
            "DISPLAY=:0.0",

cellardoor at glow in [~]   
23:05:37 › 

cellardoor at glow in [~]   
23:05:37 › echo $DISPLAY
:0

cellardoor at glow in [~]   
23:05:54 › 

````

**Comment by hurricanehrndz** [comment]
Change line 56 to this
ENV_VARS+=" --env=DISPLAY=${DISPLAY}"

**Comment by xcellardoor** [comment]
Tried both ways for the heck of it, but nothing actually appears and there are no running containers. 
````
cellardoor at glow in [~]   
23:10:01 › /usr/local/bin/firefox 
Cleaning up stopped browser-box instances...
Starting firefox...

cellardoor at glow in [~]   
23:10:11 › browser-box firefox
which: no browser-box in (/usr/sbin:/usr/bin:/sbin:/bin)
Cleaning up stopped browser-box instances...
Starting firefox...
````

**Comment by hurricanehrndz** [comment]
hmm, 

Did you try 
ENV_VARS+=" --env=DISPLAY=unix${DISPLAY}"

for line 56?

**Comment by xcellardoor** [comment]
Yup,

````
cellardoor at glow in [~]   
23:11:00 › grep DISPLAY /usr/local/bin/firefox 
  ENV_VARS+=" --env=DISPLAY=${DISPLAY}"
````

**Comment by hurricanehrndz** [comment]
LoL omg, this is strange. I wonder if you put the command you ran earlier that works in bash script and if you execute it, if it would work?

**Comment by hurricanehrndz** [comment]
Can you delete line 72 and see what happens, because it seems like you don't pass any xauthority when you ran it manually. Is your X server running fully opened?

**Comment by hurricanehrndz** [comment]
What do the docker logs for the container say by the way? Once it's stopped?

**Comment by xcellardoor** [comment]
Yep, made a test.sh with that docker command I showed earlier, and it works fine. 

Made that change and nothing happens. The X Server must be running fully open because the full length command I just used still works. It wouldn't allow that if the X server was locked down? 

````
cellardoor at glow in [~]   
23:17:13 › cat ./test.sh
docker run -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY hurricane/browser-box:latest firefox
````

I'm afraid I'm so new to Docker I've never even tried to find the logs. Where would be the best place to start?

**Comment by hurricanehrndz** [comment]
docker logs firefox

**Comment by xcellardoor** [comment]
````cellardoor at glow in [~]   
23:19:18 › docker logs firefox
Adding user `browser' ...
Adding new user `browser' (1000) with group `users' ...
Creating home directory `/home/browser' ...
Copying files from `/etc/skel' ...
usermod: group '91' does not exist
````

**Comment by hurricanehrndz** [comment]
ha ha.

**Comment by xcellardoor** [comment]
Careful! It's not my primary group. 1000 is. VIDEO is what has 91.
````
cellardoor at glow in [~]   
23:26:14 › groups
adm lp wheel uucp dbus video audio optical scanner input users vboxusers wireshark plugdev docker boinc

cellardoor at glow in [~]   
23:26:18 › getent group 91
video:x:91:cellardoor

cellardoor at glow in [~]   
23:26:39 › cat /etc/passwd | grep cellardoor
cellardoor:x:1000:100::/home/cellardoor:/bin/zsh
````

**Comment by hurricanehrndz** [comment]
Okay got it. Thank you that actually helps a lot.

**Comment by hurricanehrndz** [comment]
Okay git has been updated, can you please build and test. That should fix the issue.

**Comment by xcellardoor** [comment]
Pulled changes and rebuilt. Still just fires up the copy of Firefox that is running on my local PC I'm afraid. If I use the full command though and provide the $DISPLAY it works though :(

**Comment by hurricanehrndz** [comment]
Yeah it fires up the local instance because the wrapper scripts ensure that if the local binary is available ti will use that instead of the docker. I will make an option in the make file to override and in the install procedure to do so as well.

**Comment by hurricanehrndz** [comment]
Git is updated,

if you run the following command it should stop launching your locally available binaries.

make OVERRIDE_BROWSERS=true install

**Comment by xcellardoor** [comment]
````
cellardoor at glow in [~/github/docker/docker-browser-box]  on git:master ✔︎  0ccf200 "Allowed users to override all locally installed browsers."
11:55:35 › make OVERRIDE_BROWSERS=true install
Sending build context to Docker daemon 206.8 kB
Step 0 : FROM sameersbn/ubuntu:14.04.20150825
 ---> 2bde99560607
Step 1 : ENV TOR_VERSION 5.0.3 TOR_FINGERPRINT 0x4E2C6E8793298290
 ---> Using cache
 ---> c6fcdf73122b
Step 2 : RUN wget -q -O - "https://dl-ssl.google.com/linux/linux_signing_key.pub" | sudo apt-key add -  && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list  && apt-get update  && apt-get install -y xz-utils file locales dbus-x11 pulseaudio dmz-cursor-theme curl       fonts-dejavu fonts-liberation hicolor-icon-theme       libcanberra-gtk3-0 libcanberra-gtk-module libcanberra-gtk3-module       libasound2 libglib2.0 libgtk2.0-0 libdbus-glib-1-2 libxt6 libexif12       libgl1-mesa-glx libgl1-mesa-dri libstdc++6 nvidia-346       google-chrome-stable chromium-browser firefox  && update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX  && mkdir -p /usr/lib/tor-browser  && wget -O /tmp/tor-browser-linux64-${TOR_VERSION}_en-US.tar.xz  https://www.torproject.org/dist/torbrowser/${TOR_VERSION}/tor-browser-linux64-${TOR_VERSION}_en-US.tar.xz  && wget -O /tmp/tor-browser-linux64-${TOR_VERSION}_en-US.tar.xz.asc https://www.torproject.org/dist/torbrowser/${TOR_VERSION}/tor-browser-linux64-${TOR_VERSION}_en-US.tar.xz.asc  && mkdir ~/.gnupg  && gpg --keyserver hkp://hkps.pool.sks-keyservers.net:80 --recv-keys ${TOR_FINGERPRINT}  && gpg --fingerprint ${TOR_FINGERPRINT} | grep "Key fingerprint = EF6E 286D DA85 EA2A 4BA7  DE68 4E2C 6E87 9329 8290"  && gpg /tmp/tor-browser-linux64-${TOR_VERSION}_en-US.tar.xz.asc  && tar -Jvxf /tmp/tor-browser-linux64-${TOR_VERSION}_en-US.tar.xz --strip=1 -C /usr/lib/tor-browser  && ln -sf /usr/lib/tor-browser/Browser/start-tor-browser /usr/bin/tor-browser  && rm -rf /tmp/tor-browser-linux64-${TOR_VERSION}_en-US.tar.xz  && rm -rf ~/.gnupg  && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 2f0e18a29c19
Step 3 : COPY scripts/ /var/cache/browser-box/
Error activating devmapper device for '89e0abeb2cfe6c1a8550caa077a2363a7629fe4e2e265465007ac0a1d475f411-init': Error running DeviceCreate (ActivateDevice) dm_task_run failed
Makefile:55: recipe for target 'build' failed
make: *** [build] Error 1

````

**Comment by hurricanehrndz** [comment]
Seems like an error specific to your system, I would restart or rerun the command.

**Comment by hurricanehrndz** [comment]
This is my last build result: 
`
 wget -q -O - "https://dl-ssl.google.com/linux/linux_signing_key.pub" | sudo apt-key add -  && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list  && apt-get update  && apt-get install -y xz-utils file locales dbus-x11 pulseaudio dmz-cursor-theme curl       fonts-dejavu fonts-liberation hicolor-icon-theme       libcanberra-gtk3-0 libcanberra-gtk-module libcanberra-gtk3-module       libasound2 libglib2.0 libgtk2.0-0 libdbus-glib-1-2 libxt6 libexif12       libgl1-mesa-glx libgl1-mesa-dri libstdc++6 nvidia-346       google-chrome-stable chromium-browser firefox  && update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX  && mkdir -p /usr/lib/tor-browser  && wget -O /tmp/tor-browser-linux64-${TOR_VERSION}_en-US.tar.xz  https://www.torproject.org/dist/torbrowser/${TOR_VERSION}/tor-browser-linux64-${TOR_VERSION}_en-US.tar.xz  && wget -O /tmp/tor-browser-linux64-${TOR_VERSION}_en-US.tar.xz.asc https://www.torproject.org/dist/torbrowser/${TOR_VERSION}/tor-browser-linux64-${TOR_VERSION}_en-US.tar.xz.asc  && mkdir ~/.gnupg  && gpg --keyserver hkp://hkps.pool.sks-keyservers.net:80 --recv-keys ${TOR_FINGERPRINT}  && gpg --fingerprint ${TOR_FINGERPRINT} | grep "Key fingerprint = EF6E 286D DA85 EA2A 4BA7  DE68 4E2C 6E87 9329 8290"  && gpg /tmp/tor-browser-linux64-${TOR_VERSION}_en-US.tar.xz.asc  && tar -Jvxf /tmp/tor-browser-linux64-${TOR_VERSION}_en-US.tar.xz --strip=1 -C /usr/lib/tor-browser  && ln -sf /usr/lib/tor-browser/Browser/start-tor-browser /usr/bin/tor-browser  && rm -rf /tmp/tor-browser-linux64-${TOR_VERSION}_en-US.tar.xz  && rm -rf ~/.gnupg  && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 9c403716961b
Step 3 : COPY scripts/ /var/cache/browser-box/
 ---> df58dc2b67d4
Removing intermediate container cb5dfb89bb2b
Step 4 : COPY entrypoint.sh /sbin/entrypoint.sh
 ---> 23f75aab1e1e
Removing intermediate container f82af71dbb6c
Step 5 : COPY confs/local.conf /etc/fonts/local.conf
 ---> 5acf4ae7b6a0
Removing intermediate container 888ab791a885
Step 6 : RUN chmod 755 /sbin/entrypoint.sh
 ---> Running in 77abd973ce84
 ---> aa9ef097e2b6
Removing intermediate container 77abd973ce84
Step 7 : ENTRYPOINT /sbin/entrypoint.sh
 ---> Running in 84c35825ade3
 ---> 1322e3d53301
Removing intermediate container 84c35825ade3
Successfully built 1322e3d53301
Installing browser-box...
Installing google-chrome...
Installing google-chrome-stable...
Installing tor-browser...
Installing chromium-browser...
Installing firefox...
Installing url luancher...
Updating user to hurricanehrndz...
Updating Chrome user volume...
Updating FireFox user volume...
`

**Comment by hurricanehrndz** [comment]
By the way you can also delete lines 134-136 in the wrapper script if you don't wish to wrapper scripts to honor your local binaries. It should work now, the last bug that you found was because you have a camera, and the wrapper scripts tried to ensure that the user within the docker container had access to your camera as well.

Anyhow thanks again for all your testing.

**Comment by hurricanehrndz** [comment]
I'm going to be closing this issue, since the last couple of commits should have fixed any major problems.

**Comment by xcellardoor** [comment]
I've just wiped everything to do with browser box from Git and Docker. Will rebuild your Git now and see what happens.

**Comment by xcellardoor** [comment]
No such joy :(

To be honest I'm probably going to end up using your Docker Hub version and just pass through the X11 manually :( No idea what is happening now.

````
cellardoor at glow in [~/github/docker/docker-browser-box]  on git:master ✔︎  acc6312 "Updating documentation."
15:18:59 › /usr/local/bin/firefox 
Cleaning up stopped browser-box instances...
Error: No such image or container: 89e0abeb2cfe
Error: No such image or container: c891e525e818
Starting firefox...
````

**Comment by hurricanehrndz** [comment]
The dockerhub version was updated last night, try the following install command from the hub:

```
docker run -it --rm \
  --volume /usr/local/bin:/target \
  --env BROWSER_BOX_REPO=hurricane \
  --env OVERRIDE_BROWSERS=true \
  hurricane/browser-box:latest install
```

**Comment by hurricanehrndz** [comment]
By the way does chrome work for you?

**Comment by xcellardoor** [comment]
To be honest, I'm find setting up an alias like firefox-container and then using that to launch the command with X11 manually passed through. It still works fine, just a pity it doesn't work automatically.

And no sadly Chrome/Chromium are the same.

**Comment by hurricanehrndz** [comment]
Is the error still usermod when you run docker logs?

**Comment by xcellardoor** [comment]
Yup!
````
cellardoor at glow in [~]   
23:33:05 › browser-box firefox
which: no browser-box in (/usr/sbin:/usr/bin:/sbin:/bin)
Cleaning up stopped browser-box instances...
Starting firefox...

cellardoor at glow in [~]   
23:33:14 › docker ps -a
CONTAINER ID        IMAGE                                                              COMMAND                  CREATED             STATUS                      PORTS               NAMES
989ab094c5f9        hurricane/browser-box:latest                                       "/sbin/entrypoint.sh "   6 seconds ago       Exited (6) 5 seconds ago                        firefox
369fa8c80858        0c888254c90f53b8b8bb4d8e68a899c827123996aa359b9443f68dbf7e70d682   "/bin/sh -c 'wget -q "   33 hours ago        Exited (100) 33 hours ago                       stupefied_bohr
407f218830ef        0c888254c90f53b8b8bb4d8e68a899c827123996aa359b9443f68dbf7e70d682   "/bin/sh -c 'wget -q "   37 hours ago        Exited (100) 37 hours ago                       furious_euclid
c1ee03331e4e        0c888254c90f53b8b8bb4d8e68a899c827123996aa359b9443f68dbf7e70d682   "/bin/sh -c 'wget -q "   37 hours ago        Exited (100) 37 hours ago                       stupefied_galileo
cd072b8592e7        343516b815bb9d0052949878e7facb08ea3365923b1d4707ee5ef8cf81ecae75   "/bin/sh -c 'wget -q "   5 days ago          Exited (137) 5 days ago                         sad_swartz
c3ac041b5346        343516b815bb9d0052949878e7facb08ea3365923b1d4707ee5ef8cf81ecae75   "/bin/sh -c 'wget -q "   5 days ago          Exited (137) 5 days ago                         hungry_euclid
112d882a9558        cellardoor/sublime-text-3                                          "/usr/src/sublime_tex"   8 days ago          Exited (0) 8 days ago                           gloomy_tesla
f3933ba0a681        cellardoor/sublime-text-3                                          "/usr/src/sublime_tex"   8 days ago          Exited (0) 8 days ago                           grave_lalande
57a1d86d7698        cellardoor/sublime-text-3                                          "/usr/src/sublime_tex"   8 days ago          Exited (0) 8 days ago                           sad_ramanujan
42580a308444        jfrazelle/chrome                                                   "/usr/bin/google-chro"   2 weeks ago         Exited (137) 2 weeks ago                        naughty_meitner
fe0048e17d5b        jess/tor-proxy                                                     "tor -f /etc/tor/torr"   2 weeks ago         Exited (0) 11 days ago                          torproxy
a69bd15fd1ba        debian                                                             "/bin/bash"              2 weeks ago         Exited (0) 2 weeks ago                          backstabbing_goldstine
05624ea2786d        debian                                                             "/bin/bash"              2 weeks ago         Exited (0) 2 weeks ago                          adoring_thompson

cellardoor at glow in [~]   
23:33:19 › docker logs firefox
Adding user `browser' ...
Adding new user `browser' (1000) with group `users' ...
Creating home directory `/home/browser' ...
Copying files from `/etc/skel' ...
usermod: group '91' does not exist
````

**Comment by hurricanehrndz** [comment]
I don't have any video cameras so its hard for me to test this.

**Comment by xcellardoor** [comment]
Can you strip out anything and everything related to /dev/video or whatever it is trying to do?

**Comment by hurricanehrndz** [comment]
I could, but then chrome,firefox and all browsers won't have access to the cameras.

**Comment by xcellardoor** [comment]
To be honest, most people don't use the cameras day-to-day anyway? Perhaps worth a try if it is an easy fix?

**Comment by hurricanehrndz** [comment]
I'm pretty sure I got it. Arch and debian use different gid for video. Argh!!!! I'm will trigger a build.

**Comment by hurricanehrndz** [comment]
Issue will be closed. I'm assuming its fixed.

**Comment by xcellardoor** [comment]
I'd forgotten about this sorry, I'm pulling your latest image now. Remind me how I run the containerised Firefox/Chromium without doing the browser-box full system install. I want my _real_ firefox to remain the default one launched by my system. Thanks.

**Comment by hurricanehrndz** [comment]
just run the normal install command in the readme, the wrapper will respect the local binaries. You will need to call the wrapper script instead and each browser as parameter.

i.e. browser-box firefox

**Comment by xcellardoor** [comment]
IT WORKS!!

**Comment by hurricanehrndz** [comment]
Cool, does the chrome one work too?

**Comment by xcellardoor** [comment]
Yes!! Mark this as resolved :+1:
